# Generated by Django 6.0 on 2025-12-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('FOOD_TRUCK', 'Food Truck'), ('DROP_OFF', 'Drop Off'), ('FULL_SERVICE', 'Full Service Drop Off')], max_length=50)),
                ('event_date', models.DateField()),
                ('event_address', models.CharField(max_length=500)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(verbose_name='Tell Us More')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
