# Generated by Django 6.0 on 2026-01-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Current Food Truck Menu', max_length=100)),
                ('pdf_file', models.FileField(upload_to='menus/pdf/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
