# Generated by Django 6.0 on 2026-04-16 19:04

import django.core.validators
import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtruckmenu',
            options={'verbose_name': 'Menu Upload', 'verbose_name_plural': 'Menu Uploads'},
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='cta_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='foodtruckmenu',
            name='pdf_file',
            field=models.FileField(upload_to='menus/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), restaurant.models.validate_file_size]),
        ),
    ]
