# Generated by Django 6.0 on 2026-04-21 19:03

import django.core.validators
import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_update_menu_image_urls_to_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruckmenu',
            name='pdf_url',
            field=models.URLField(blank=True, default='', help_text='Paste a direct PDF URL (e.g. Google Drive embed link) to use instead of uploading a file.'),
        ),
        migrations.AlterField(
            model_name='foodtruckmenu',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to='menus/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), restaurant.models.validate_file_size]),
        ),
    ]
