# Generated by Django 6.0 on 2026-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_add_pdf_url_to_foodtruckmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringrequest',
            name='number_of_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
